language: python
python:
    - "3.7"

install: make bootstrap
script: make

deploy:

  - provider: script
    script: make package
    on:
      tags: true

  - provider: pypi
    user: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true