language: python
python:
    - "3.7"
cache:
  pip: true

script: make

deploy:

  - provider: script
    script: make package
    on:
      tags: true

  - provider: pypi
    user: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true

  - provider: script
    script: make doc
    after_success:
      bash .github/deploy-gh-pages.sh
    on:
      tags: true
