language: python
python:
    - "3.7"
cache:
  pip: true

script: make

deploy:

  - provider: script
    script: make package doc
    on:
      tags: true

  - provider: pypi
    user: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true

  - provider: pages
    local_dir: doc/build/phc
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true
