name: Release SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.LIFEOMIC_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.LIFEOMIC_PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          make test doc
          ./publish.sh
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/phc
