name: Release SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pipx install poetry==1.5.1
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.LIFEOMIC_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.LIFEOMIC_PYPI_TOKEN }}
        run: |
          poetry run poe lint
          poetry run pytest
          poetry run poe doc
          ./publish.sh
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/phc
