name: Release SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.8.5

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # pdoc works under this version
          cache: "poetry"

      - run: poetry install
      - run: |
          poetry run poe lint
          poetry run pytest
          poetry run poe doc

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.LIFEOMIC_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.LIFEOMIC_PYPI_TOKEN }}
        run: |
          ./publish.sh
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/phc
