name: Release SDK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.LIFEOMIC_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.LIFEOMIC_PYPI_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        make test package doc deploy
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/build/phc